### ISSUE TITLE
Classe PedidoVenda

### ISSUE THREAD

**Issue by profRenatoOliveira1** [Anajuh15/elitecar-backend#1]
Ana Júlia, na classe PedidoVenda, o idPedido não pode estar no construtor pois no momento que vamos cadastrar um novo pedido, ainda não vamos ter esse ID pois ele é gerado pelo banco de dados.

Você precisa tirar o idPedido do construtor e atribuir o valor 0 na definição deste atributo.

**Comment by Anajuh15** [comment]
verificado

**Comment by profRenatoOliveira1** [comment]
Correto!
